{% do validate_shared_context() %}
{{ config(
    materialized='incremental',
    schema='mart',
    unique_key='job_id',
    incremental_strategy='delete+insert',
    on_schema_change='sync_all_columns',
    post_hook="{{ purge_unscoped_shared_rows() }}",
    tags=['shared', 'mart', 'motherduck']
) }}

select
    job_id,
    source as source_name,
    source_job_id,
    job_title as title,
    normalized_title,
    company as company_name,
    normalized_company,
    location,
    location_normalized,
    location_group,
    industry,
    seniority,
    work_arrangement,
    employment_type,
    visa_signal,
    salary_min,
    salary_max,
    'USD' as salary_currency,
    salary_midpoint,
    salary_range_text,
    posted_at,
    date_posted,
    jd_post_link as apply_url,
    apply_link,
    job_description,
    md5(coalesce(normalized_description, job_description, '')) as job_description_hash,
    normalized_description,
    first_seen_at,
    last_seen_at,
    connector_run_uuid,
    true as is_active,
    inserted_at as updated_at
from {{ ref('int_job_posts_deduped') }}
